version: '3.8'

services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    command: npm run preview
    networks:
      - app-network

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "6465:6465"
    networks:
      - app-network
      
    command: ["node", "dist/main.js"]

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge
