export const placeCategories = [
  {
    title: "Accommodation",
    types: ["Lodging"],
  },
  {
    title: "Food & Drink",
    types: [
      "Bakery",
      "Bar",
      "Cafe",
      "Meal Delivery",
      "Meal Takeaway",
      "Restaurant",
    ],
  },
  {
    title: "Entertainment & Recreation",
    types: [
      "Amusement Park",
      "Aquarium",
      "Art Gallery",
      "Bowling Alley",
      "Casino",
      "Movie Rental",
      "Movie Theater",
      "Museum",
      "Night Club",
      "Spa",
      "Stadium",
      "Tourist Attraction",
      "Zoo",
    ],
  },
  {
    title: "Financial Services",
    types: ["Accounting", "ATM", "Bank", "Finance"],
  },
  {
    title: "Government & Civic",
    types: [
      "City Hall",
      "Courthouse",
      "Embassy",
      "Fire Station",
      "Local Government Office",
      "Police",
      "Post Office",
    ],
  },
  {
    title: "Healthcare Services",
    types: [
      "Dentist",
      "Doctor",
      "Hospital",
      "Pharmacy",
      "Physiotherapist",
      "Veterinary Care",
    ],
  },
  {
    title: "Personal Services",
    types: ["Beauty Salon", "Hair Care", "Laundry", "Spa"],
  },
  {
    title: "Religious",
    types: ["Church", "Hindu Temple", "Mosque", "Synagogue"],
  },
  {
    title: "Educational",
    types: ["School", "University"],
  },
  {
    title: "Retail",
    types: [
      "Bicycle Store",
      "Book Store",
      "Clothing Store",
      "Convenience Store",
      "Department Store",
      "Electronics Store",
      "Furniture Store",
      "Grocery or Supermarket",
      "Hardware Store",
      "Home Goods Store",
      "Jewelry Store",
      "Liquor Store",
      "Pet Store",
      "Shoe Store",
      "Shopping Mall",
      "Store",
    ],
  },
  {
    title: "Transport & Auto",
    types: [
      "Airport",
      "Bus Station",
      "Car Dealer",
      "Car Rental",
      "Car Repair",
      "Car Wash",
      "Gas Station",
      "Light Rail Station",
      "Parking",
      "Subway Station",
      "Taxi Stand",
      "Train Station",
      "Transit Station",
    ],
  },
  {
    title: "Outdoors",
    types: ["Campground", "Park"],
  },
  {
    title: "Other",
    types: [
      "Accounting",
      "Cemetery",
      "Electrician",
      "Funeral Home",
      "General Contractor",
      "Insurance Agency",
      "Lawyer",
      "Library",
      "Locksmith",
      "Moving Company",
      "Painter",
      "Plumber",
      "Real Estate Agency",
      "Roofing Contractor",
      "Storage",
      "Travel Agency",
    ],
  },
  {
    title: "Administrative Areas (Regions)",
    types: [
      "Administrative Area Level 1",
      "Administrative Area Level 2",
      "Administrative Area Level 3",
      "Colloquial Area",
      "Country",
      "Locality",
      "Neighborhood",
      "Political",
      "Postal Code",
      "Postal Code Prefix",
      "Postal Code Suffix",
      "Postal Town",
      "Sublocality",
      "Sublocality Level 1",
      "Sublocality Level 2",
      "Sublocality Level 3",
      "Sublocality Level 4",
      "Sublocality Level 5",
    ],
  },
  {
    title: "Geographical",
    types: ["Natural Feature", "Point of Interest"],
  },
];
